name: Infra Workflow
on: push
env:
  aws_region: 'ap-south-1'

jobs:
  base-nonlive:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/nonlive/base
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.NONLIVE_AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.NONLIVE_AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.aws_region }}
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: "0.13.6"
#
#      - name: Terraform Init
#        run: terraform init
#
#      - name: Terraform Plan
#        run: terraform plan
#
#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: terraform apply -auto-approve

  api-nonlive:
    runs-on: ubuntu-latest
    needs: base-nonlive
    defaults:
      run:
        working-directory: terraform/nonlive/api
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.NONLIVE_AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.NONLIVE_AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.aws_region }}
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: "0.13.6"
#
#      - name: Terraform Init
#        run: terraform init
#
#      - name: Terraform Plan
#        run: terraform plan
#
#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: terraform apply -auto-approve

  frontend-nonlive:
    runs-on: ubuntu-latest
    needs: base-nonlive
    defaults:
      run:
        working-directory: terraform/nonlive/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.NONLIVE_AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.NONLIVE_AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.aws_region }}
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: "0.13.6"
#
#      - name: Terraform Init
#        run: terraform init
#
#      - name: Terraform Plan
#        run: terraform plan
#
#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: terraform apply -auto-approve
